### ISSUE TITLE
[Release-1.0] Design and build comments section

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/Gruvee#14]
## General
Grüvee will be utilizing commenting per song. This is outlined in the MVP and has designs setup for it. Currently there are sketch designs that have been created. This issue is to finalize the design and develop the ui/ux for Android and iOS. 

## Tasks
- [x] Finalize UI/UX in Sketch
- [x] Generate a component that can handle the comments 
- [x] Setup an action to open and close comments section and/or pop an overlay for comments
- [x] Verify design is functional on both Android and iOS

## Screenshots
Here are the current ideas for the comments section:
<img width="748" alt="Screen Shot 2019-10-28 at 7 53 11 PM" src="https://user-images.githubusercontent.com/13204620/67733813-975af800-f9bc-11e9-875f-b3970a5c3d85.png">
<img width="380" alt="Screen Shot 2019-10-28 at 7 53 02 PM" src="https://user-images.githubusercontent.com/13204620/67733814-975af800-f9bc-11e9-8eac-ff030d856c26.png">

**Comment by adilanchian** [comment]
Spent most of today trying to deal with the height issue when adding the comments section to our songitem. A lot of things going on here, but basically we need to set the height on the SwipeRow component. This seems to have some implications for the playlist list view that we will also need to look into.

There is also potentially a bug in the SwipeRow library we are using, but with the method listed above we can get around it

**Comment by adilanchian** [comment]
We are having a lot of issues with nested scroll views. TL;DR can't scroll a FlatList inside another FlatList which is essentially what we have. There is a solution here: https://github.com/facebook/react-native/issues/1966

There is also another option to change how we render the comments sections. We can push out to a new view or even set an overlay. This might be the preferred option.

**Comment by adilanchian** [comment]
Alrighty, decided to go to a completely different view for comments. In the process of designing the flatlist view and adding in the proper actions

**Comment by adilanchian** [comment]
- Make sure to hide delete action if the comment was not written by you
- Fix delete action not being fully hidden
- Setup proper state

**Comment by adilanchian** [comment]
Next things needed here are:
- Add comment section
- Update state for newly added comments
- MAYBE add ability to like comments / ability to reply to specific comments

**Comment by adilanchian** [comment]
COMMENTS ARE LIVE. Checking to make sure this works on Android is next and then we can MOVE ONE.

**Comment by adilanchian** [comment]
WE DONE FAM.
